services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'frontend-journey:${TAG:-latest}'
    container_name: frontend-journey
    ports:
      - '4000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
